const ROUTE_MAP = {
  root: "/",
  login: "/login",
  register: "/register",
  medical_assessments: "/medical-assessments",
  upcoming_medical_assessments: "/upcoming-medical-assessments",
  capture_location: "/capture-location",
  medical_assessment_options: "/medical-assessment-options",
  nursing_options: "/nursing-options",
  paramedical_options: "/paramedical-options",
  assessment_type: "/assessment-type",
  hospital_forms: "/hospital-forms",
  osce_options: "/osce-options",
  forgot_password: "/forgot-password",
  nursing: "/nursing",
  nursing_non_medical: "/nursing-non-medical",
  paramedical: "/paramedical",
  paramedical_non_medical: "/paramedical-non-medical",
  osce_1: "/osce-1",
  osce_2: "/osce-2",
  basic_infrastructure: "/basic-infrastructure",
  student_info: "/student-info",
  facilities: "/facilities",
  faculty_and_facilities: "/faculty-&-facilities",
  quality_of_processes: "/quality-of-processes",
  labs: "/labs",
  osce_unoccupied_beds: "/osce-unoccupied-beds",
  vital_signs: "/vital-signs",
  osceForm_param_osceName: "/osceForm/",
  nursing_param_formName: "/nursingForms/",
  paramedical_param_formName: "/paramedicalForm/",
  otherforms_param_formName: "/forms/",
  admin: "/admin",
  root_star: "/*",
};

export default ROUTE_MAP;
